// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn("Supabase credentials strongly recommended for full functionality. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment variables.");
}

const rawSupabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder-ais.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Create a proxy to handle calls when Supabase is not configured
// This allows the app to be explored in demo mode without crashing on fetches
export const supabase = new Proxy(rawSupabase, {
  get(target, prop, receiver) {
    if (!isSupabaseConfigured) {
      if (prop === 'auth') {
        return {
          signInWithPassword: () => Promise.resolve({ data: { user: { id: 'demo' }, session: {} }, error: null }),
          signUp: () => Promise.resolve({ data: { user: { id: 'demo' }, session: {} }, error: null }),
          signOut: () => Promise.resolve({ error: null }),
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
          getSession: () => Promise.resolve({ data: { session: null }, error: null }),
          getUser: () => Promise.resolve({ data: { user: null }, error: null }),
        };
      }
      if (prop === 'from' || prop === 'rpc' || prop === 'storage') {
        if (prop === 'storage') {
        return {
          from: () => ({
            upload: () => Promise.resolve({ data: { path: 'demo' }, error: null }),
            getPublicUrl: () => ({ data: { publicUrl: '' } }),
            list: () => Promise.resolve({ data: [], error: null }),
            remove: () => Promise.resolve({ data: [], error: null }),
          })
        };
      }
      
      const noopQuery: any = () => ({
        select: noopQuery,
        insert: noopQuery,
        update: noopQuery,
        upsert: noopQuery,
        delete: noopQuery,
        eq: noopQuery,
        neq: noopQuery,
        gt: noopQuery,
        gte: noopQuery,
        lt: noopQuery,
        lte: noopQuery,
        like: noopQuery,
        ilike: noopQuery,
        is: noopQuery,
        in: noopQuery,
        contains: noopQuery,
        containedBy: noopQuery,
        rangeGt: noopQuery,
        rangeGte: noopQuery,
        rangeLt: noopQuery,
        rangeLte: noopQuery,
        rangeAdjacent: noopQuery,
        overlaps: noopQuery,
        match: noopQuery,
        not: noopQuery,
        or: noopQuery,
        filter: noopQuery,
        order: noopQuery,
        limit: noopQuery,
        range: noopQuery,
        single: () => Promise.resolve({ data: null, error: null }),
        maybeSingle: () => Promise.resolve({ data: null, error: null }),
        csv: noopQuery,
        then: (cb: any) => Promise.resolve({ data: [], error: null }).then(cb),
      });
      return noopQuery;
      }
    }
    return Reflect.get(target, prop, receiver);
  },
});
